name: xpu-test
'on':
  workflow_call:
    inputs:
      build-environment:
        required: true
        type: string
        description: Top-level label for what's being built/tested.
      test-matrix:
        required: true
        type: string
        description: JSON description of what test configs to run.
      docker-image:
        required: true
        type: string
        description: Docker image to run in.
      sync-tag:
        required: false
        type: string
        default: ''
        description: 'If this is set, our linter will use this to make sure that every
          other

          job with the same `sync-tag` is identical.

          '
      timeout-minutes:
        required: false
        type: number
        default: 390
        description: 'Set the maximum (in minutes) how long the workflow should take
          to finish

          '
      tests-to-include:
        required: false
        type: string
        default: ''
        description: 'List of tests to include (empty string implies default list)

          '
      dashboard-tag:
        required: false
        type: string
        default: ''
      disable-monitor:
        description: '[Experimental] Disable utilization monitoring for tests.

          Currently, by default we disable the monitor job and only look for specific
          tests,

          since we are investigating the behaviour of the monitor script with different
          tests.

          '
        required: false
        type: boolean
        default: true
      monitor-log-interval:
        description: 'Set the interval for the monitor script to log utilization.

          '
        required: false
        type: number
        default: 5
      monitor-data-collect-interval:
        description: 'Set the interval for the monitor script to collect data.

          '
        required: false
        type: number
        default: 1
    secrets:
      HUGGING_FACE_HUB_TOKEN:
        required: false
        description: 'HF Auth token to avoid rate limits when downloading models or
          datasets from hub

          '
permissions:
  id-token: write
  contents: read
env:
  GIT_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
jobs:
  test:
    if: github.repository_owner == 'playground-nils' && toJSON(fromJSON(inputs.test-matrix).include)
      != '[]'
    strategy:
      matrix: ${{ fromJSON(inputs.test-matrix) }}
      fail-fast: false
    timeout-minutes: ${{ matrix.mem_leak_check == 'mem_leak_check' && 600 || inputs.timeout-minutes
      }}
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout PyTorch
      uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
    - name: Setup XPU
      uses: ./.github/actions/setup-xpu
    - name: Calculate docker image
      id: calculate-docker-image
      uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
      with:
        docker-image-name: ${{ inputs.docker-image }}
    - name: Use following to pull public copy of the image
      id: print-ghcr-mirror
      env:
        ECR_DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
      shell: bash
      run: 'tag=${ECR_DOCKER_IMAGE##*:}

        echo "docker pull ghcr.io/pytorch/ci-image:${tag/:/-}"

        '
    - name: Pull docker image
      uses: pytorch/test-infra/.github/actions/pull-docker-image@main
      with:
        docker-image: ${{ steps.calculate-docker-image.outputs.docker-image }}
    - name: Get workflow job id
      id: get-job-id
      uses: ./.github/actions/get-workflow-job-id
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Start monitoring script
      id: monitor-script
      if: ${{ !inputs.disable-monitor }}
      shell: bash
      continue-on-error: true
      env:
        JOB_ID: ${{ steps.get-job-id.outputs.job-id }}
        JOB_NAME: ${{ steps.get-job-id.outputs.job-name }}
        WORKFLOW_NAME: ${{ github.workflow }}
        WORKFLOW_RUN_ID: ${{github.run_id}}
        MONITOR_LOG_INTERVAL: ${{ inputs.monitor-log-interval }}
        MONITOR_DATA_COLLECT_INTERVAL: ${{ inputs.monitor-data-collect-interval }}
      run: 'python3 -m pip install psutil==5.9.8 dataclasses_json==0.6.7 nvidia-ml-py==11.525.84

        python3 -m tools.stats.monitor --log-interval "$MONITOR_LOG_INTERVAL" --data-collect-interval
        "$MONITOR_DATA_COLLECT_INTERVAL" > usage_log.txt 2>&1 &

        echo "monitor-script-pid=${!}" >> "${GITHUB_OUTPUT}"

        '
    - name: Download build artifacts
      uses: ./.github/actions/download-build-artifacts
      with:
        name: ${{ inputs.build-environment }}
    - name: Parse ref
      id: parse-ref
      run: .github/scripts/parse_ref.py
    - name: Check for keep-going label and re-enabled test issues
      id: keep-going
      uses: ./.github/actions/filter-test-configs
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-matrix: ${{ inputs.test-matrix }}
        job-name: ${{ steps.get-job-id.outputs.job-name }}
    - name: Set Test step time
      id: test-timeout
      shell: bash
      env:
        JOB_TIMEOUT: ${{ matrix.mem_leak_check == 'mem_leak_check' && 600 || inputs.timeout-minutes
          }}
      run: 'echo "timeout=$((JOB_TIMEOUT-30))" >> "${GITHUB_OUTPUT}"

        '
    - name: Test
      id: test
      env:
        BUILD_ENVIRONMENT: ${{ inputs.build-environment }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_JOB: ${{ github.job }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        JOB_ID: ${{ steps.get-job-id.outputs.job-id }}
        JOB_NAME: ${{ steps.get-job-id.outputs.job-name }}
        BRANCH: ${{ steps.parse-ref.outputs.branch }}
        SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
        PYTORCH_RETRY_TEST_CASES: 1
        PYTORCH_OVERRIDE_FLAKY_SIGNAL: 1
        CONTINUE_THROUGH_ERROR: ${{ steps.keep-going.outputs.keep-going }}
        TEST_SHOWLOCALS: ${{ steps.keep-going.outputs.ci-test-showlocals }}
        VERBOSE_TEST_LOGS: ${{ steps.keep-going.outputs.ci-verbose-test-logs }}
        NO_TEST_TIMEOUT: ${{ steps.keep-going.outputs.ci-no-test-timeout }}
        NO_TD: ${{ steps.keep-going.outputs.ci-no-td }}
        TEST_CONFIG: ${{ matrix.config }}
        SHARD_NUMBER: ${{ matrix.shard }}
        NUM_TEST_SHARDS: ${{ matrix.num_shards }}
        REENABLED_ISSUES: ${{ steps.keep-going.outputs.reenabled-issues }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        XLA_CLANG_CACHE_S3_BUCKET_NAME: ossci-compiler-clang-cache-circleci-xla
        PYTORCH_TEST_CUDA_MEM_LEAK_CHECK: ${{ matrix.mem_leak_check && '1' || '0'
          }}
        PYTORCH_TEST_RERUN_DISABLED_TESTS: ${{ matrix.rerun_disabled_tests && '1'
          || '0' }}
        TESTS_TO_INCLUDE: ${{ inputs.tests-to-include }}
        DASHBOARD_TAG: ${{ inputs.dashboard-tag }}
        HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      timeout-minutes: ${{ fromJson(steps.test-timeout.outputs.timeout) }}
      run: "# Fetch aws credential from IMDs\neval \"$(python3 .github/scripts/get_aws_session_tokens.py)\"\
        \nset -x\n\nTEST_COMMAND=.ci/pytorch/test.sh\n\n# detached container should\
        \ get cleaned up by teardown_ec2_linux\n# Used for GPU_FLAG since that doesn't\
        \ play nice\n# shellcheck disable=SC2086,SC2090\ncontainer_name=$(docker run\
        \ \\\n  ${GPU_FLAG:-} \\\n  -e BUILD_ENVIRONMENT \\\n  -e PR_NUMBER \\\n \
        \ -e GITHUB_ACTIONS \\\n  -e GITHUB_REPOSITORY \\\n  -e GITHUB_WORKFLOW \\\
        \n  -e GITHUB_JOB \\\n  -e GITHUB_RUN_ID \\\n  -e GITHUB_RUN_NUMBER \\\n \
        \ -e GITHUB_RUN_ATTEMPT \\\n  -e JOB_ID \\\n  -e BRANCH \\\n  -e SHA1 \\\n\
        \  -e AWS_DEFAULT_REGION \\\n  -e AWS_ACCESS_KEY_ID \\\n  -e AWS_SECRET_ACCESS_KEY\
        \ \\\n  -e AWS_SESSION_TOKEN \\\n  -e IN_WHEEL_TEST \\\n  -e SHARD_NUMBER\
        \ \\\n  -e TEST_CONFIG \\\n  -e NUM_TEST_SHARDS \\\n  -e REENABLED_ISSUES\
        \ \\\n  -e PYTORCH_RETRY_TEST_CASES \\\n  -e PYTORCH_OVERRIDE_FLAKY_SIGNAL\
        \ \\\n  -e CONTINUE_THROUGH_ERROR \\\n  -e VERBOSE_TEST_LOGS \\\n  -e TEST_SHOWLOCALS\
        \ \\\n  -e NO_TEST_TIMEOUT \\\n  -e NO_TD \\\n  -e MAX_JOBS=\"$(nproc --ignore=2)\"\
        \ \\\n  -e SCCACHE_BUCKET \\\n  -e SCCACHE_REGION \\\n  -e SCCACHE_S3_KEY_PREFIX\
        \ \\\n  -e XLA_CLANG_CACHE_S3_BUCKET_NAME \\\n  -e PYTORCH_TEST_CUDA_MEM_LEAK_CHECK\
        \ \\\n  -e PYTORCH_TEST_RERUN_DISABLED_TESTS \\\n  -e TESTS_TO_INCLUDE \\\n\
        \  -e ZE_AFFINITY_MASK \\\n  -e HUGGING_FACE_HUB_TOKEN \\\n  -e DASHBOARD_TAG\
        \ \\\n  --env-file=\"${RUNNER_TEMP}/github_env_${GITHUB_RUN_ID}\" \\\n  --ulimit\
        \ stack=10485760:83886080 \\\n  --ulimit core=0 \\\n  --security-opt seccomp=unconfined\
        \ \\\n  --cap-add=SYS_PTRACE \\\n  --shm-size=\"8g\" \\\n  --tty \\\n  --detach\
        \ \\\n  --name=\"${container_name}\" \\\n  --user jenkins \\\n  --privileged\
        \ \\\n  -v \"${GITHUB_WORKSPACE}:/var/lib/jenkins/workspace\" \\\n  -w /var/lib/jenkins/workspace\
        \ \\\n  \"${DOCKER_IMAGE}\"\n)\n# save container name for later step\necho\
        \ \"CONTAINER_NAME=${container_name}\" >> \"$GITHUB_ENV\"\n# jenkins user\
        \ does not have write permission to mounted workspace; work-around by copying\
        \ within container to jenkins home\ndocker exec -t \"${container_name}\" sh\
        \ -c \"cd .. && cp -R workspace pytorch && cd pytorch && pip install dist/*.whl\
        \ && ${TEST_COMMAND}\"\n"
    - name: Save test results
      if: always()
      run: '# copy test results back to the mounted workspace, needed sudo, resulting
        permissions were correct

        docker exec -t "${{ env.CONTAINER_NAME }}" sh -c "cd ../pytorch && sudo cp
        -R test/test-reports ../workspace/test"

        '
    - name: Change permissions
      if: ${{ always() && steps.test.conclusion }}
      run: 'docker exec -t "${{ env.CONTAINER_NAME }}" sh -c "sudo chown -R 1000:1000
        test"

        '
    - name: Print remaining test logs
      shell: bash
      if: always() && steps.test.conclusion
      run: 'cat test/**/*_toprint.log || true

        '
    - name: Stop monitoring script
      if: ${{ always() && steps.monitor-script.outputs.monitor-script-pid }}
      shell: bash
      continue-on-error: true
      env:
        MONITOR_SCRIPT_PID: ${{ steps.monitor-script.outputs.monitor-script-pid }}
      run: 'kill "$MONITOR_SCRIPT_PID"

        '
    - name: Upload test artifacts
      uses: ./.github/actions/upload-test-artifacts
      if: always() && steps.test.conclusion && steps.test.conclusion != 'skipped'
      with:
        use-gha: true
        file-suffix: ${{ github.job }}-${{ matrix.config }}-${{ matrix.shard }}-${{
          matrix.num_shards }}-${{ matrix.runner }}_${{ steps.get-job-id.outputs.job-id
          }}
    - name: Upload utilization stats
      if: ${{ always() && steps.test.conclusion && steps.test.conclusion != 'skipped'
        && !inputs.disable-monitor }}
      continue-on-error: true
      uses: ./.github/actions/upload-utilization-stats
      with:
        job_id: ${{ steps.get-job-id.outputs.job-id }}
        job_name: ${{ steps.get-job-id.outputs.job-name }}
        workflow_name: ${{ github.workflow }}
        workflow_run_id: ${{github.run_id}}
        workflow_attempt: ${{github.run_attempt}}
    - name: Collect backtraces from coredumps (if any)
      if: always()
      run: '# shellcheck disable=SC2156

        find . -iname "core.[1-9]*" -exec docker exec "${CONTAINER_NAME}" sh -c "gdb
        python {} -ex ''bt'' -ex ''q''" \;

        '
    - name: Stop container before exit
      if: always()
      run: '# Workaround for multiple runners on same IDC node

        docker stop "${{ env.CONTAINER_NAME }}"

        '
    - name: Store Core dumps on GitHub
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: failure()
      with:
        name: coredumps-${{ matrix.config }}-${{ matrix.shard }}-${{ matrix.num_shards
          }}-${{ matrix.runner }}
        retention-days: 14
        if-no-files-found: ignore
        path: ./**/core.[1-9]*
    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
      with:
        role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_upload-benchmark-results
        role-duration-seconds: 18000
        aws-region: us-east-1
    - name: Upload the benchmark results
      uses: pytorch/test-infra/.github/actions/upload-benchmark-results@main
      with:
        benchmark-results-dir: test/test-reports
        dry-run: false
        schema-version: v3
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Teardown XPU
      uses: ./.github/actions/teardown-xpu
